import { Injectable } from "@nestjs/common";
import * as PDFDocument from "pdfkit";
import { Buffer } from "buffer";

@Injectable()
export class PDFGenerationService {
  async generateAgreement(content: string, agreementNumber: string): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({ margin: 50 });
      const chunks: Buffer[] = [];

      doc.on("data", (chunk) => chunks.push(chunk));
      doc.on("end", () => resolve(Buffer.concat(chunks)));
      doc.on("error", reject);

      // Header
      doc.fontSize(20).text("RENTAL AGREEMENT", { align: "center" });
      doc.moveDown();
      doc.fontSize(12).text(`Ref: ${agreementNumber}`, { align: "right" });
      doc.moveDown();

      // Body
      doc.fontSize(10).text(content, {
        align: "justify",
        lineGap: 5
      });

      // Footer
      doc.moveDown(2);
      doc.fillColor("grey").text("Generated by Chioma Housing Protocol", { align: "center" });

      doc.end();
    });
  }
}
